name: CD


on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:


jobs:
  tag-latest:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add tag latest to staged image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:staging
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:staging ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:latest
  restart-compose-production:
    needs: tag-latest
    runs-on: ubuntu-latest

    steps:
      - name: Restart docker compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            REPO_DIR="~/elibrary/projects/production"
            ENV_DIR="~/elibrary/envs/production"
  
            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              git reset --hard
              git pull
            else
              mkdir -p "$REPO_DIR"
              git clone https://github.com/ElectronicLibraryRT/production-docker-compose.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi
  
            cp "$ENV_DIR/.env.postgres" "$REPO_DIR/"
            cp "$ENV_DIR/.env.minio" "$REPO_DIR/"
            cp "$ENV_DIR/.env.backend" "$REPO_DIR/"
            cp "$ENV_DIR/.env.frontend" "$REPO_DIR/"
  
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export FRONTEND_IMAGE=${{ vars.FRONTEND_IMAGE }}
            export BACKEND_IMAGE=${{ vars.BACKEND_IMAGE }}
  
            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f
    
  restart-compose-frontend-env:
    needs: tag-latest
    runs-on: ubuntu-latest

    steps:
      - name: Restart docker compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            REPO_DIR="~/elibrary/projects/frontend-env"
            ENV_DIR="~/elibrary/envs/frontend-env
  
            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              git reset --hard
              git pull
            else
              mkdir -p "$REPO_DIR"
              git clone https://github.com/ElectronicLibraryRT/frontend-env-docker-compose.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi
  
            cp "$ENV_DIR/.env.postgres" "$REPO_DIR/"
            cp "$ENV_DIR/.env.minio" "$REPO_DIR/"
            cp "$ENV_DIR/.env.backend" "$REPO_DIR/"
            cp "$ENV_DIR/.env.frontend" "$REPO_DIR/"
  
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export BACKEND_IMAGE=${{ vars.BACKEND_IMAGE }}
  
            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f
