name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Checkstyle
        run: |
          CHECKSTYLE_VERSION="10.25.1"
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-$CHECKSTYLE_VERSION/checkstyle-$CHECKSTYLE_VERSION-all.jar -O checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c ./checkstyle.xml src/

  build-and-push:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine branch source
        id: branch-source
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]_.-/' | tr '/' '-')
          
          echo "sanitized_branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:staging-${{ steps.branch-source.outputs.sanitized_branch }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:buildcache,mode=max

  run-api-tests:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout tests-compose repository
      uses: actions/checkout@v4
      with:
        repository: ElectronicLibraryRT/api-tests-docker-compose

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Docker Compose tests
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        export API_TESTS_IMAGE=${{ vars.API_TESTS_IMAGE }}
        export BACKEND_IMAGE=${{ vars.BACKEND_IMAGE }}

        export BACKEND_TAG=staging-${{ needs.build-and-push.outputs.sanitized_branch }}
        export API_TESTS_TAG=${{ needs.build-and-push.outputs.sanitized_branch }}
        
        docker compose up --exit-code-from api-tests

  tag-latest:
    needs: run-api-tests
    runs-on: ubuntu-latest
  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Add tag latest to staged image
        run: |
          STAGING_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:staging-${{ needs.build-and-push.outputs.sanitized_branch }}
          STAGED_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ needs.build-and-push.outputs.sanitized_branch }}
          docker pull $STAGING_IMAGE
          docker tag $STAGING_IMAGE $STAGED_IMAGE
          docker push $STAGED_IMAGE
